server:
  port: 80

# Thymeleaf 설정
spring:
  application:
    name: KBoard
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  #datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user326
    password: 1234

  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: aa
            client-secret: aa
            scope:
              - email
              - profile
#          facebook:
#            client-id:
#            client-secret:
#            scope: #접근권한
#              - email
#              - public-profile

          naver:
            client-id: aa
            client-secret: aa
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 10 # 한 [페이징] 당 몇개의 페이지 표시
    page_rows: 10  # 한 '페이지' 에 몇개의 글을 리스트 할지
  # 파일 업로드 경로
  upload:
    path: upload

  # OAuth2
  oauth2:
    password: 1234 # oauth2 인증한 회원에 대한 전용 패스워드, 보안주의!
    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: aa
      redirect-uri: http://localhost:8080/oauth2/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청 URI